/**
 * Lead-gen automation blueprints — the proven, hard-coded cadences every client
 * gets on onboarding. Timing lives here (battle-tested); the COPY for each
 * message step is generated by Claude at onboard time (tailored to the client),
 * with the `fallback` copy used if generation fails so a workflow is never empty.
 *
 * Message steps carry: { type, brief, fallback }.
 *   send_sms   fallback: string
 *   send_email fallback: { subject, html }
 * Structural steps: { type: 'wait', minutes|hours|days }, { type: 'add_tag'|'remove_tag', tag }.
 *
 * All copy may use merge tags: {{firstName}} {{lastName}} {{fullName}} {{business}}
 * {{repName}} {{bookingLink}} {{offer}} {{email}} {{phone}}.
 */

const emailWrap = (inner, cta) => `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;font-size:15px;line-height:1.6;color:#222;max-width:560px">`
  + inner
  + (cta ? `<p style="margin:24px 0"><a href="{{bookingLink}}" style="background:#7c3aed;color:#fff;text-decoration:none;padding:12px 22px;border-radius:10px;display:inline-block;font-weight:600">${cta}</a></p>` : '')
  + `<p style="margin-top:24px;color:#555">— {{repName}}, {{business}}</p></div>`

export const BLUEPRINTS = [
  {
    key: 'speed-to-lead',
    name: 'Speed-to-Lead Blitz',
    description: 'Instant SMS + email the moment a lead arrives, then a rapid first-week follow-up cadence until they reply. This is the highest-ROI automation.',
    isSpeedToLead: true,
    steps: [
      { type: 'send_sms',  brief: 'Instant first text within seconds of the lead opting in. Warm, personal, from the rep. Reference the offer and ask one easy yes/no question to start a conversation. Under 160 chars.',
        fallback: "Hi {{firstName}}, it's {{repName}} with {{business}} — saw you're interested in {{offer}}. Still looking to get started? Reply YES and I'll help. 👍" },
      { type: 'send_email', brief: 'Instant welcome email confirming we received their interest, restating the offer value, and pushing to book a time. Friendly, short, one clear CTA button.',
        fallback: { subject: 'Quick hello from {{business}} 👋', html: emailWrap(`<p>Hi {{firstName}},</p><p>Thanks for your interest in <b>{{offer}}</b>! I'd love to help you get started. The fastest way is to grab a quick time on my calendar:</p>`, 'Book your free time') } },
      { type: 'wait', minutes: 5 },
      { type: 'send_sms',  brief: "5-minute nudge if they haven't replied. Light, helpful, not pushy. Offer to answer questions. Under 160 chars.",
        fallback: "{{firstName}}, just making sure you saw my text! Happy to answer any questions about {{offer}}. What's the best time to chat?" },
      { type: 'wait', minutes: 30 },
      { type: 'send_sms',  brief: '30-minute follow-up. Add a small bit of social proof or urgency. Under 160 chars.',
        fallback: "We're helping a lot of folks with {{offer}} right now, {{firstName}} — spots fill up fast. Want me to hold one for you? {{bookingLink}}" },
      { type: 'wait', hours: 1 },
      { type: 'send_email', brief: 'One-hour value email: briefly explain how it works / what to expect, address a common objection, CTA to book.',
        fallback: { subject: 'How {{business}} can help you, {{firstName}}', html: emailWrap(`<p>Hi {{firstName}},</p><p>Wanted to make this easy for you. Here's how it works: we start with a quick, no-pressure call to understand what you need, then map out the fastest path to results with {{offer}}.</p><p>Pick a time that works for you:</p>`, 'Grab a time') } },
      { type: 'wait', days: 1 },
      { type: 'send_sms',  brief: 'Day-1 check-in. Personal, brief, assume good intent (they got busy). Under 160 chars.',
        fallback: "Hey {{firstName}}, I know things get busy! Still happy to help you with {{offer}} whenever you're ready. Just reply here. — {{repName}}" },
      { type: 'wait', days: 2 },
      { type: 'send_email', brief: 'Day-3 value + light urgency email. Recap the benefit, add a testimonial-style line, strong CTA.',
        fallback: { subject: "Still interested, {{firstName}}?", html: emailWrap(`<p>Hi {{firstName}},</p><p>I don't want you to miss out on {{offer}}. Our clients tell us the hardest part was waiting to start. Let's get you going — it only takes a few minutes to book:</p>`, 'Book now') } },
      { type: 'wait', days: 4 },
      { type: 'send_sms',  brief: 'Day-7 last-chance text. Polite breakup / final nudge. Under 160 chars.',
        fallback: "{{firstName}}, I'll close out your file for now — but if you ever want help with {{offer}}, just text me here. Door's always open! — {{repName}}" },
      { type: 'add_tag', tag: 'contacted' },
    ],
  },

  {
    key: 'nurture',
    name: 'Long-Term Nurture',
    description: 'A value-led 30–60 day drip for leads who did not convert fast — most leads buy after many touches.',
    steps: [
      { type: 'send_email', brief: 'Kickoff value email: a genuinely useful tip related to the offer, no hard sell, soft CTA.',
        fallback: { subject: 'A quick tip for you, {{firstName}}', html: emailWrap(`<p>Hi {{firstName}},</p><p>While you're considering {{offer}}, here's something useful: the people who get the best results are the ones who start with a clear plan. Whenever you're ready, I'm here to build that with you.</p>`, 'Talk to {{repName}}') } },
      { type: 'wait', days: 10 },
      { type: 'send_sms',  brief: 'Day-10 helpful check-in text, value-first. Under 160 chars.',
        fallback: "{{firstName}}, thinking about {{offer}}? Happy to share what's worked for others in your situation — no pressure. — {{repName}}, {{business}}" },
      { type: 'wait', days: 4 },
      { type: 'send_email', brief: 'Day-14 story/social-proof email: a short before/after style win, soft CTA.',
        fallback: { subject: 'What {{offer}} did for someone like you', html: emailWrap(`<p>Hi {{firstName}},</p><p>Quick story: someone came to us unsure if {{offer}} was right for them. A few weeks later they couldn't believe they waited. If you want to see what that could look like for you, let's chat.</p>`, 'See if it fits') } },
      { type: 'wait', days: 7 },
      { type: 'send_sms',  brief: 'Day-21 light, friendly nudge. Under 160 chars.',
        fallback: "Still here whenever you want to explore {{offer}}, {{firstName}}! Reply anytime. — {{repName}}" },
      { type: 'wait', days: 9 },
      { type: 'send_email', brief: 'Day-30 offer email: make a clear, compelling case to act now with a reason.',
        fallback: { subject: "Let's make it happen, {{firstName}}", html: emailWrap(`<p>Hi {{firstName}},</p><p>It's been a few weeks — I'd still love to help you with {{offer}}. If now's the time, here's the easiest next step:</p>`, 'Get started') } },
      { type: 'wait', days: 15 },
      { type: 'send_sms',  brief: 'Day-45 value nudge. Under 160 chars.',
        fallback: "{{firstName}}, checking in one more time about {{offer}} — still happy to help if it's useful. — {{repName}}" },
      { type: 'wait', days: 15 },
      { type: 'send_email', brief: 'Day-60 wrap-up email: warm, low-pressure, leave the door open.',
        fallback: { subject: 'Door is always open', html: emailWrap(`<p>Hi {{firstName}},</p><p>I'll ease off the emails for now — but {{business}} is always here if you want help with {{offer}} down the road. Just reply and I'll jump back in.</p>`, '') } },
      { type: 'add_tag', tag: 'nurtured' },
    ],
  },

  {
    key: 'appointment',
    name: 'Appointment Sequence',
    description: 'Confirms a booked appointment and sends reminders to maximize show-up rate.',
    steps: [
      { type: 'send_sms',  brief: 'Immediate booking confirmation with enthusiasm and the booking/details link. Under 160 chars.',
        fallback: "You're booked, {{firstName}}! 🎉 Looking forward to it. Need to reschedule? {{bookingLink}} — {{repName}}, {{business}}" },
      { type: 'send_email', brief: 'Confirmation email with what to expect on the call/appointment and the link to manage it.',
        fallback: { subject: "You're confirmed with {{business}}", html: emailWrap(`<p>Hi {{firstName}},</p><p>Your appointment is confirmed — can't wait to talk about {{offer}}. On the call we'll keep it simple: understand your goals and map the next step. If you need to reschedule, use the link below.</p>`, 'View / reschedule') } },
      { type: 'wait', days: 1 },
      { type: 'send_sms',  brief: 'Reminder ~a day out, friendly, restate value, include link. Under 160 chars.',
        fallback: "Hi {{firstName}}, quick reminder about your time with {{business}} coming up! Anything you want me to prep? {{bookingLink}}" },
      { type: 'send_email', brief: 'Reminder email with a tip to get the most out of the appointment and the link.',
        fallback: { subject: 'Looking forward to our chat, {{firstName}}', html: emailWrap(`<p>Hi {{firstName}},</p><p>Reminder about our upcoming time together. To get the most out of it, jot down your top question about {{offer}} beforehand. See you soon!</p>`, 'Manage booking') } },
      { type: 'add_tag', tag: 'appointment-confirmed' },
    ],
  },

  {
    key: 'no-show',
    name: 'No-Show Recovery',
    description: 'Wins back leads who missed their appointment.',
    steps: [
      { type: 'send_sms',  brief: 'Immediate, gracious "we missed you" text with an easy rebook link. No guilt. Under 160 chars.',
        fallback: "Hey {{firstName}}, looks like we missed each other! No worries at all — grab a new time whenever works: {{bookingLink}} — {{repName}}" },
      { type: 'send_email', brief: 'Gracious no-show email, assume life happened, make rebooking one click.',
        fallback: { subject: 'We missed you, {{firstName}} — let\'s reschedule', html: emailWrap(`<p>Hi {{firstName}},</p><p>Life happens! I'd still love to help you with {{offer}}. Pick a new time that's easier for you:</p>`, 'Rebook in 30 seconds') } },
      { type: 'wait', days: 1 },
      { type: 'send_sms',  brief: 'Next-day rebook nudge, warm. Under 160 chars.',
        fallback: "{{firstName}}, still want to chat about {{offer}}? Here's my calendar whenever you're ready: {{bookingLink}}" },
      { type: 'wait', days: 3 },
      { type: 'send_email', brief: 'Final rebook email with a touch of urgency and reassurance.',
        fallback: { subject: 'One more try, {{firstName}}', html: emailWrap(`<p>Hi {{firstName}},</p><p>I'll keep a spot open a little longer. If {{offer}} is still on your mind, let's finally connect:</p>`, 'Grab the last spot') } },
      { type: 'add_tag', tag: 'no-show-followup' },
    ],
  },

  {
    key: 'reactivation',
    name: 'Database Reactivation',
    description: 'Re-engages cold/unconverted leads at 30/60/90 days.',
    steps: [
      { type: 'send_sms',  brief: 'Friendly "still interested?" reopener. Under 160 chars.',
        fallback: "Hi {{firstName}}, it's {{repName}} at {{business}}. Still thinking about {{offer}}? We've got some new openings — want details?" },
      { type: 'wait', days: 1 },
      { type: 'send_email', brief: 'Reopener email: what\'s new / why now, clear CTA.',
        fallback: { subject: "Still interested in {{offer}}, {{firstName}}?", html: emailWrap(`<p>Hi {{firstName}},</p><p>It's been a little while! We've had some exciting updates around {{offer}} and I thought of you. If the timing's better now, let's pick it back up:</p>`, "Let's reconnect") } },
      { type: 'wait', days: 29 },
      { type: 'send_sms',  brief: '~Day-30 win-back with a reason to act. Under 160 chars.',
        fallback: "{{firstName}}, quick one — we have limited spots for {{offer}} this month. Want me to save you one? — {{repName}}" },
      { type: 'wait', days: 30 },
      { type: 'send_email', brief: '~Day-60 stronger offer/incentive email.',
        fallback: { subject: 'A little nudge, {{firstName}}', html: emailWrap(`<p>Hi {{firstName}},</p><p>I'd hate for you to miss out on {{offer}}. If you've been waiting for the right moment, this is a great one. Here's the easy next step:</p>`, 'Claim your spot') } },
      { type: 'wait', days: 30 },
      { type: 'send_sms',  brief: '~Day-90 last reactivation text, breakup tone. Under 160 chars.',
        fallback: "Last check-in, {{firstName}} — if {{offer}} is ever back on your radar, just text me here anytime. — {{repName}}, {{business}}" },
      { type: 'add_tag', tag: 'reactivation-sent' },
    ],
  },

  {
    key: 'review-referral',
    name: 'Won → Review + Referral',
    description: 'After a win: thank the client, ask for a review, then ask for referrals.',
    steps: [
      { type: 'send_sms',  brief: 'Warm thank-you text right after winning. Under 160 chars.',
        fallback: "{{firstName}}, thank you for trusting {{business}}! 🙏 It's a pleasure working with you. — {{repName}}" },
      { type: 'send_email', brief: 'Thank-you email reinforcing the relationship and what\'s next.',
        fallback: { subject: 'Thank you, {{firstName}}!', html: emailWrap(`<p>Hi {{firstName}},</p><p>Thank you for choosing {{business}} — we're thrilled to have you. We're committed to getting you a great result with {{offer}}. If you ever need anything, just reply.</p>`, '') } },
      { type: 'wait', days: 2 },
      { type: 'send_email', brief: 'Google review request: make it effortless, explain it helps others find them.',
        fallback: { subject: 'Quick favor, {{firstName}}?', html: emailWrap(`<p>Hi {{firstName}},</p><p>If you've had a good experience with {{business}}, would you mind leaving us a quick review? It takes 30 seconds and genuinely helps other people find us. Thank you so much!</p>`, 'Leave a review') } },
      { type: 'add_tag', tag: 'review-requested' },
      { type: 'wait', days: 5 },
      { type: 'send_sms',  brief: 'Referral ask text — friendly, specific. Under 160 chars.',
        fallback: "{{firstName}}, know anyone who could use {{offer}}? We'd love to help them too — send them my way and I'll take great care of them! — {{repName}}" },
      { type: 'add_tag', tag: 'referral-requested' },
    ],
  },
]

/** Steps that carry copy (need AI generation), in order, with their channel + brief. */
export function messageSteps(bp) {
  return bp.steps
    .map((s, i) => ({ ...s, index: i }))
    .filter(s => s.type === 'send_sms' || s.type === 'send_email')
}

/** Build engine-format steps for a blueprint, applying generated copy where present. */
export function assembleSteps(bp, copyByIndex = {}) {
  return bp.steps.map((s, i) => {
    if (s.type === 'send_sms') {
      const c = copyByIndex[i]
      return { type: 'send_sms', body: (c && c.text) || s.fallback }
    }
    if (s.type === 'send_email') {
      const c = copyByIndex[i]
      return {
        type: 'send_email',
        subject: (c && c.subject) || s.fallback?.subject || '',
        body:    (c && c.html)    || s.fallback?.html || '',
      }
    }
    if (s.type === 'wait') {
      return { ...s } // already { type:'wait', minutes|hours|days }
    }
    if (s.type === 'add_tag' || s.type === 'remove_tag') {
      return { type: s.type, tag: s.tag }
    }
    return { type: s.type }
  })
}
